extend type Mutation {
  """
  ✨ Insert a single `Class` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  class_insert(
    """
    Data object to insert into the table.
    """
    data: Class_Data!
  ): Class_KeyOutput! @fdc_generated(from: "Class", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Document` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insert(
    """
    Data object to insert into the table.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Registration` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  registration_insert(
    """
    Data object to insert into the table.
    """
    data: Registration_Data!
  ): Registration_KeyOutput! @fdc_generated(from: "Registration", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Student` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insert(
    """
    Data object to insert into the table.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Class` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  class_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Class_Data!]!
  ): [Class_KeyOutput!]! @fdc_generated(from: "Class", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Document` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  document_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Registration` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  registration_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Registration_Data!]!
  ): [Registration_KeyOutput!]! @fdc_generated(from: "Registration", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Student` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  student_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Class` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Class`.
  """
  class_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Class_Data!
  ): Class_KeyOutput! @fdc_generated(from: "Class", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Document` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Document_Data!
  ): Document_KeyOutput! @fdc_generated(from: "Document", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Registration` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Registration`.
  """
  registration_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Registration_Data!
  ): Registration_KeyOutput! @fdc_generated(from: "Registration", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Student` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Student_Data!
  ): Student_KeyOutput! @fdc_generated(from: "Student", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Class` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Class`.
  """
  class_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Class_Data!]!
  ): [Class_KeyOutput!]! @fdc_generated(from: "Class", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Document` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Document`.
  """
  document_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Document_Data!]!
  ): [Document_KeyOutput!]! @fdc_generated(from: "Document", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Registration` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Registration`.
  """
  registration_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Registration_Data!]!
  ): [Registration_KeyOutput!]! @fdc_generated(from: "Registration", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Student` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Student`.
  """
  student_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Student_Data!]!
  ): [Student_KeyOutput!]! @fdc_generated(from: "Student", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Class` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Class` or `null` if not found.
  """
  class_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Class_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Class_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Class_Data!
  ): Class_KeyOutput @fdc_generated(from: "Class", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Document` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Document` or `null` if not found.
  """
  document_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Document_Data!
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Registration` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Registration` or `null` if not found.
  """
  registration_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Registration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Registration_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Registration_Data!
  ): Registration_KeyOutput @fdc_generated(from: "Registration", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Student` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Student` or `null` if not found.
  """
  student_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Student_Data!
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Class` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  class_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Class_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Class_Data!
  ): Int! @fdc_generated(from: "Class", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Document` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  document_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Document_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Document_Data!
  ): Int! @fdc_generated(from: "Document", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Registration` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  registration_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Registration_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Registration_Data!
  ): Int! @fdc_generated(from: "Registration", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Student` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  student_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Student_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Student_Data!
  ): Int! @fdc_generated(from: "Student", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Class` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  class_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Class_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Class_FirstRow
  ): Class_KeyOutput @fdc_generated(from: "Class", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Document` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  document_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Document_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Document_FirstRow
  ): Document_KeyOutput @fdc_generated(from: "Document", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Registration` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  registration_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Registration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Registration_FirstRow
  ): Registration_KeyOutput @fdc_generated(from: "Registration", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Student` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  student_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Student_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Student_FirstRow
  ): Student_KeyOutput @fdc_generated(from: "Student", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Class` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  class_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Class_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Class", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Document` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  document_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Document_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Document", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Registration` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  registration_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Registration_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Registration", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Student` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  student_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Student_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Student", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
